spring.jmx:
  enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: inventory
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sql:
    init:
      continue-on-error: true
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    password: alex
    username: alex
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:alexDb





